# Generated by Django 4.1 on 2024-06-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_delete_access',
            field=models.BooleanField(default=False),
        ),
    ]
