# Generated by Django 4.1 on 2024-06-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCloudURI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=200, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255)),
                ('video_start_time', models.DateTimeField()),
                ('video_end_time', models.DateTimeField()),
                ('camera_angle', models.CharField(max_length=255, null=True)),
                ('onedrive_url', models.URLField()),
            ],
        ),
    ]
