# Generated by Django 4.1 on 2024-05-24 07:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='VideoFile',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='\\datavolume\\Servershare\\meenakshi\\DMS-latest\\UploadedVideos'), upload_to='UploadedVideos/'),
        ),
    ]
