# Generated by Django 4.1 on 2024-06-19 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0002_newclouduri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='company_name',
        ),
        migrations.AddField(
            model_name='newclouduri',
            name='company_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newclouduri',
            name='project_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.DateTimeField(),
        ),
    ]
