# Generated by Django 4.2 on 2024-06-06 17:43

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0003_clouduri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clouduri',
            old_name='cloud_uri',
            new_name='onedrive_url',
        ),
        migrations.AddField(
            model_name='clouduri',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='camera_angle',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vfms.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vfms.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vfms.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vfms.role'),
        ),
        migrations.AlterField(
            model_name='videofiles',
            name='VideoFile',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='UploadedVideos'), upload_to='UploadedVideos/'),
        ),
    ]
