# Generated by Django 4.1 on 2024-05-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0003_clouduri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.TimeField(),
        ),
    ]
