# Generated by Django 4.1 on 2024-06-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0003_remove_project_company_name_newclouduri_company_id_and_more'),
    ]

    operations = [
    ]
