# Generated by Django 4.1 on 2024-05-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0004_alter_clouduri_video_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clouduri',
            old_name='cloud_uri',
            new_name='onedrive_url',
        ),
    ]
