# Generated by Django 4.1 on 2024-05-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0006_clouduri_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
