# Generated by Django 4.1 on 2024-05-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0007_company_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='userid',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
