# Generated by Django 4.1 on 2024-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0008_project_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.TimeField(null=True),
        ),
    ]
