# Generated by Django 4.1 on 2024-05-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0009_alter_clouduri_video_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
