# Generated by Django 4.1 on 2024-05-30 12:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0010_project_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
