# Generated by Django 4.1 on 2024-05-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0011_alter_clouduri_video_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clouduri',
            name='camera_angle',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
