# Generated by Django 4.1 on 2024-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0012_clouduri_camera_angle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloud_File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
    ]
