# Generated by Django 4.1 on 2024-05-30 11:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0013_cloud_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloud_file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
