# Generated by Django 4.2 on 2024-06-06 15:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0016_alter_location_project_alter_user_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videofiles',
            name='VideoFile',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='UploadedVideos'), upload_to='UploadedVideos/'),
        ),
    ]
