# Generated by Django 4.2 on 2024-06-06 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0017_alter_videofiles_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
