# Generated by Django 4.2 on 2024-06-06 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0019_alter_clouduri_video_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
