# Generated by Django 4.2 on 2024-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vfms', '0020_alter_clouduri_video_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clouduri',
            name='video_end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='clouduri',
            name='video_start_time',
            field=models.DateTimeField(),
        ),
    ]
